name: Build and deploy on  EC2

on:
  push:
    branches:
    -  main

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mentalpirate/python-flask:latest
      - name: deploy_to_ec2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PUBLIC_KEY }}
          script: |
            sudo docker login -u mentalpirate -p {{ secrets.DOCKERHUB_TOKEN }}
            sudo docker pull mentalpirate/python-flask:latest
            sudo docker stop pyflask 2>/dev/null
            sudo docker run -d --rm -p 5000:5000 --name pyflask  mentalpirate/python-flask:latest 
  
