name: Build and deploy on  EC2

on:
  push:
    branches: main

jobs:
  build_docker_image:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mentalpirate/python-flask:latest
      -
        name: start_container_ec2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PUBLIC_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker pull mentalpirate/python-flask:latest
            sudo start -d -p 5000:5000 mentalpirate/python-latest 
  
